# Market Making Configuration for Binance Testnet
# This file contains default settings for your trading bot

[strategy]
name = "market_making"
symbols = ["ETHUSDT"]
base_spread_pct = 0.2        # 0.2% spread
order_levels = 3             # 3 levels of orders
max_capital = 1000.0         # Maximum capital to deploy
leverage = 10                # Leverage for futures trading
testnet = true               # Using Binance testnet

[risk_management]
max_drawdown = 0.15          # 15% maximum drawdown
max_position_size = 500.0    # Maximum position size per symbol
var_95_limit = 0.05          # 5% VaR limit
stop_loss_pct = 0.05         # 5% stop loss
take_profit_pct = 0.10       # 10% take profit
risk_check_interval = 30     # Risk check every 30 seconds

[exchange]
name = "binance_testnet"
base_url = "https://testnet.binancefuture.com"
api_key_env = "BINANCE_API_KEY"
api_secret_env = "BINANCE_API_SECRET"
rate_limit = 1200            # Requests per minute
order_timeout = 30           # Order timeout in seconds

[llm_optimization]
enabled = true
model = "gpt-4"
api_key_env = "OPENAI_API_KEY"
optimization_objective = "sharpe_ratio"
max_generations = 20
population_size = 50
backtest_days = 365

[multi_exchange]
enabled = false              # Disabled for testnet
exchanges = ["binance"]      # Only Binance for testnet
arbitrage_threshold = 0.5    # 0.5% minimum arbitrage
min_profit = 10.0           # Minimum profit threshold

[agent_swarm]
enabled = true
swarm_size = 3
agent_types = ["market_maker", "arbitrage", "risk_manager"]
consensus_threshold = 0.6
enable_learning = true
communication_interval = 60  # Inter-agent communication every 60s

[monitoring]
log_level = "INFO"
metrics_interval = 300       # Log metrics every 5 minutes
performance_tracking = true
alert_thresholds = { drawdown = 0.10, loss_streak = 5 }

[advanced]
enable_machine_learning = false  # Disabled for initial testing
sentiment_analysis = false       # Disabled for testnet
news_integration = false         # Disabled for testnet
cross_chain = false             # Disabled for testnet
